### ISSUE TITLE
Give grid cell/tiles various properties

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#100]
Currently, there is an undocumented feature about "mud" tiles which are not detectable by Reeborg but will cause the program to stop if he steps on it.

There should be a way to give properties to "tiles" such as
* detectable  (via `front_is_clear()`)
* impassable (blocks the way)
* fatal obstacle (program ends if Reeborg steps on that tile)

At a future point, it might be desirable to change the behaviour of a tile based on some property (like time steps, or whether or not Reeborg has stepped on that tile at least once) so that it could suddenly become impassable or be a fatal obstacle.   However, this should not be considered until the simpler case described above has been implemented.

**Comment by Goldsong** [comment]
Ok.. tiles are not the same as walls.  They could be though but at this moment a wall is always impassable and fatal.  Is there any reason to change that?

Now some ideas for the properties, taking it from André's idea of adding slidable tiles:

detectable (i.e., observable):  grandfather's clock vs mud.  At this moment a wall is not a tile... 
impassable: grandfather's clock vs token (or closed door vs. open door)
fatal: mud vs. grass (here we probably do not want into tiles that 'kill' the robot, like tiles that would shock him or pits or something like that... or do we?  hot lava tiles? Ice tiles? are water tiles fatal?)
'take'able: grandfather's clock vs. token
slideable: grandfather's clock vs. token (I guess this property of the tile varies depending on whether there is a wall behind it as seen from the robots position.  BTW, does pushing a slideable tile pushes a second slideable tile behind it?
teleport: at this moment these tiles do not exist but whole games have being built around this concept.
pressable: buttons on the floor?

On many of the new tiles there is a sense that a tile is attached to another tile. For example, a teleport tile, in principle, would teleport the robot to another particular tile. Likewise, a slideable tilemight be pushed or not whether a second pushable tile is being pushed against it. Tiles that are buttons can activate a different tile far away, e.g, standing on the button changes a tile from that of a closed door to one of an open door.

This is looking more and more like a programmable video game.

**Comment by aroberge** [comment]
I like these ideas.  Also, I should include an option to specify a maximum number of robots in a given world.  A certain task may require the help of another robot (perhaps to trigger some button, or push a box so that it can sunk in the mud, making a bridge for the other robot).

This does indeed start looking more and more like a programmable video game.   However, I also do not want to lose the focus: it should remain easy to create simple worlds.

Perhaps, instead of attempting to have a World Editor that can handle every instance, I should keep it simple, for simple worlds, and write a guide on how to edit world files to go beyond what the World Editor can do.  I thought I saw some projects that exist allowing one to embed json file format editors which could probably be easily used for this purpose.

**Comment by aroberge** [comment]
Reading the description of the many possible tiles in a previous comment .... The way I see tiles is that they are static in that they are drawn once, on a background canvas, and do not change while the program is run.  Objects, on the other hand, are drawn on a different canvas that is "above" the background canvas - but below the canvas where the robots are drawn.

**Comment by aroberge** [comment]
5 different tiles now exist.  The looks of "gravel" and "ice" are likely a bit too much similar.  We can see the boundaries between grass tiles very clearly ... which is not altogether a bad idea.  I like though that gravel (and mud) appear to be seemless.

You can see the tiles "definitions" at https://github.com/aroberge/reeborg/blob/master/src/js/tiles.js

Two tiles that have an interesting behaviour resulted in additional code in https://github.com/aroberge/reeborg/blob/master/src/js/control.js#L40

In addition, everytime a frame is recorded, the following check is performed: https://github.com/aroberge/reeborg/blob/master/src/js/recorder.js#L280

As you can see, the code is fairly contained and generic; it should be easy, if desired, to add new tiles with custom behaviour.  For example, we could have a teleportation tile that moves a robot to another location.

The code for drawing the tiles is also fairly simple, making use of two functions that appear consecutively starting at https://github.com/aroberge/reeborg/blob/master/src/js/visible_world.js#L362

(One exception is the "home" tile ... which also should get a new treatment, allowing to simplify the rest of the code quite a bit.)

Right now, dealing with objects is quite elaborate.  I'd like to use a similar approach and simplify the code significantly; however, this is going to require a fair bit of time to get it right.

As usual, comments/suggestions are welcome!    [I have not spent much time on the world editor - just enough to be able to create worlds with the new tiles; I'll wait until after implementing the new objects to reorganize everything].

Note that some old worlds *might* very well be broken, as I have change the world format slightly.  They will definitely be broken once I implement the new ways to deal with objects, and you will have to recreate your existing worlds if you want to use the "dev" version.

**Comment by aroberge** [comment]
This is now referenced elsewhere; no need to keep it open as a separate, active issue.
