### ISSUE TITLE
Simplification suggested: remove say(), the diary panel, etc.

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#104]
Right now, Reeborg can output text with Python using three commands:  `write()`, `say()` and `print()`; with Javascript, it's with `say()` and `write()`, as `print()` calls up the printer interface to print the entire web page!
Initially, `say()` was not available; I thought that floating windows for the print output would interfere too much and that it was better to have a dedicated panel for output.  However, it appears that some (all?) teachers' experience has lead them to prefer to use `say()`.
I propose to remove the current diary panel and have the `print` output appear in a floating panel (called Reeborg's diary) like the current output of `say`.   However, currently a new call to `say` results in clearing up the previous output; this would be changed so that the print output is cumulative (i.e. nothing is erased until the world is "reset").

**Comment by aroberge** [comment]
I further suggest that the default location should be aligned such that the output (floating) window appears at the bottom left of the browser window, and could still be repositioned by the user.  Once open, this window would remain open unless closed explicitly by the user.
Note that, currently, this window (unlike the diary) currently displays unformatted (html) text.  In the new proposal, the text would appear in a pre-formatted html element (like it currently does for the `print()` function).

**Comment by aroberge** [comment]
Taken care of in development version.  Follow in #111

**Comment by dz0** [comment]
write could append newline by default (like print in Python or console.log in JS)

**Comment by aroberge** [comment]
`write` should no longer be used in Python programs.
