### ISSUE TITLE
input() not in sync with program

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#110]
When a user calls input(), this is done before any robot motion takes place, and does not reflect where it is called in the program.  Ideally, this should be done differently ... but I don't see any obvious way to do this.

**Comment by dz0** [comment]
Skulpt does it somehow with [suspensions](https://github.com/skulpt/skulpt/search?utf8=%E2%9C%93&q=suspension)

[example](//trinket.io/embed/python#code=name%20%3D%20input(%22Who%20are%20you%3F%22)%20%20%20%20%0Aprint%20%22Hi%22%2C%20name)

**Comment by aroberge** [comment]
I will forward the information to the Brython folks.
