### ISSUE TITLE
More robust highlighting

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#112]
Currently, lines of code can be highlighted in the editor while executing only if statements are on one line.  Thus, the following valid Python code:

    move(
              )

can not be highlighted.  The highlighting process is done by inserting special instructions for the editor.  For example, when a user runs this program:

    move()
    turn_left()
    move()

what is really run is something like the following

    highlight_line(0)
    move()
    highlight_line(1)
    turn_left()
    highlight_line(2)
    move()

Obviously, it is a bit more complicated than this so that `for/while loops`, `def` and `if/elif/else` type statements, which introduce indented code blocks are handled correctly.  Still the current highlighting code found at
https://github.com/aroberge/reeborg/blob/master/src/libraries/brython/Lib/site-packages/highlight.py
only works if no multi-line statements are present.

A nice enhancement would be to improve upon the existing code so that multi-line statements could be handled appropriately.

**Comment by aroberge** [comment]
Done - ready for testing.

**Comment by dz0** [comment]
test
```py

move()
write("hello", 
      5)
x = 0
while front_is_clear(
                  
                  ):
     x = (x 
        +
        1)
     move(
        )
     write( x, "\n"  )
```
works in word_dev.html :)

**Comment by aroberge** [comment]
You might want to use `print` instead of `write`, since `print` now works as expected from a Python program.  `write` is an equivalent javascript function (since `print` in javascript calls up the printer dialog).

**Comment by aroberge** [comment]
@dz0 @goldstone  Code hightlighting should be more robust and give fewer false positive.  Prior to the last change, if a syntax error was preventing code highlighting, highlighting was automatically turned off with a message to the user AND an error dialog was shown indicating that a syntax error was found.

Now, if a SyntaxError (or any other standard Python exception) is raised, and if syntax highlighting was used by the programmer, it is automatically turned back on with no indication to the programmer that it had been turned off.   (At least, that's the way it should work)

There is one valid Python construction that automatically cause highlighting to be turned off: if the user enters a single backslash at the end of a line, indicating that the statement continues on the next line.  If this is done, highlighting is turned off automatically.    I do not plan to change this behaviour even if someone were to submit code to handle it:  using a backslash at the end of line is very error-prone as a single space inserted after the backslash causes a syntax error. This is usually impossible to detect when reading the code (unless the editor used has a way to show spaces) and should be discouraged; it is far better to use parentheses to group lines of code into a single statement.

**Comment by aroberge** [comment]
@dz0 Both `print` and `write` are essentially aliases of `RUR.control.write`.  As you know, `print` can have an optional argument `end` to change the including `\n` automatically.  

`write` is definitely not a function that should be taught to people learning to program with Python.  When using Javascript, `write` becomes something useful and, in that context, it would not make sense to automatically include `\n`: students need to learn about the newline character and using `write` provides the proper context to do so (and the only context now that the redundant `say` has been removed).

**Comment by aroberge** [comment]
Closing this issue now as it appears that the major goal has been accomplished.  Any related problem noted should result in a new issue.
