### ISSUE TITLE
deleted function is remembered from previous run

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#114]
This doesn't give an error, if def was uncomented in previous run
```py
# def do(): move()

do()
```

But should give: 
```NameError

do
→ undefined: do()
```

**Comment by aroberge** [comment]
Yes, this is a problem.  I tried to address it (when it comes to the library) with the code in https://github.com/aroberge/reeborg/blob/master/src/libraries/brython/Lib/site-packages/common_def.py but I seem to recall running through some problems when trying to do the same with locals()/globals().  this will need to be investigated further.

**Comment by aroberge** [comment]
This should now be fixed and ready for testing.

**Comment by aroberge** [comment]
Previous attempt to fix apparently created other problems.  Reverted the change until I have more time to investigate.

**Comment by aroberge** [comment]
Ok, should be fixed now.

**Comment by aroberge** [comment]
Fixed in development version; too involved to fix in "stable" version (without causing other problems).
