### ISSUE TITLE
On NameError  automatically rerun without highlighting

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#115]
```py
for i in range(n):  
        move()          
```
shows
```
Unexplained Error

Please turn highlighting off
and try running your program again
```
****
it could automatically turn it off and show:
```
NameError
n
```

**Comment by aroberge** [comment]
Yes, something like this would make sense.  Perhaps I should still have some warning indicating that an error was found and highlighting will be automatically turned off.

**Comment by aroberge** [comment]
This error messages is no longer given, as part of the work done for issue #117.
