### ISSUE TITLE
Code analysis (warnings) for most common dummy errors

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#117]
I notice several common errors, which lead beginners to frustration as is hard to notice:

- missing parentheses after command 
```py
if front_is_clear:
     move()
```
this could be checked for standart Reeborg commands...

- students with experience of other languages, tend to forget colon or confuse it with semicolon
```py
if front_is_clear();
     move()
```
```py
if front_is_clear()
     move()
```
Maybe it's possible to detect such SyntaxError and give explanation, what to correct?

**Comment by aroberge** [comment]
This goes well beyond what I could hope to implement.  I chose to use a standard interpreter so that I would not have to try to implement my own.

**Comment by dz0** [comment]
Maybe regexp would be enough - ar least for parentheses case :-)
Maybe I could trys this  during summer

**Comment by Goldsong** [comment]
I submitted a patch to check for both missing semicolons and missing parentheses from function headers.

**Comment by aroberge** [comment]
The code written would likely be very close to what is needed. However, I am thinking of changing it a bit, mostly where and when it is executed.   If I write:

    while (not token_here and
               front_is_clear):
               move()

I'm almost certain that the code would indicate an error and prevent the (valid) program from running. This is the same problem that `highlight` has and with which @Goldsong is very familiar.

The approach I intend to follow instead is to trigger the syntax analysis **only** if/when a SyntaxError is raised, and analyze it at that point; this avoid creating false positives due to a faulty analysis of valid code.

  What is suggested in this issue is similar to what I was doing with Crunchy  where I was attempting to provide a simplified traceback ... translated in the user's language.  (This is something I intend to do here as well). (see https://github.com/aroberge/crunchy/blob/master/crunchy/src/errors_3k.py#L102).  However, since the tracebacks provided by Brython do not seem to follow the exact same syntax as the Python ones, I intend to use a different approach. First, I use the information provided by the traceback to locate which line is triggering the error; then, I would use the code written by @Goldsong to analyze the program focusing around that line of code to see if more information would need to be added.

[This brings another point which I just thought of and will file as an issue: now that the world creator can add code to be run before the user's program, the line numbers might very well be very misleading when such code is present; this will need to be investigated.]

**Comment by aroberge** [comment]
I am going to remove completely the existing error analysis (which **is** simplifying **some** tracebacks) from the development version and reimplement it from scratch, incorporating the code written by @Goldsong as well taking care of issues #119 and #115.

**Comment by Goldsong** [comment]
> On May 19, 2015, at 5:12 AM, André Roberge <notifications@github.com> wrote:
> 
> The code written would likely be very close to what is needed. However, I am thinking of changing it a bit, mostly where and when it is executed. If I write:
> 
> while (not token_here and
>            front_is_clear):
>            move()
> I'm almost certain that the code would indicate an error and prevent the (valid) program from running. This is the same problem that highlight has and with which @Goldsong <https://github.com/Goldsong> is very familiar.
> 
You are correct; the snipped would trigger an error where there is none.  
> The approach I intend to follow instead is to trigger the syntax analysis only if/when a SyntaxError is raised, and analyze it at that point; this avoid creating false positives due to a faulty analysis of valid code.
> 
> What is suggested in this issue is similar to what I was doing with Crunchy where I was attempting to provide a simplified traceback ... translated in the user's language. (This is something I intend to do here as well). (see https://github.com/aroberge/crunchy/blob/master/crunchy/src/errors_3k.py#L102 <https://github.com/aroberge/crunchy/blob/master/crunchy/src/errors_3k.py#L102>). However, since the tracebacks provided by Brython do not seem to follow the exact same syntax as the Python ones, I intend to use a different approach. First, I use the information provided by the traceback to locate which line is triggering the error; then, I would use the code written by @Goldsong <https://github.com/Goldsong> to analyze the program focusing around that line of code to see if more information would need to be added.
> 
Yes.. this would work better than the stand alone code.  The correct solutioin, which would be an interesting to work on but it is probably over my head, would be to use a parser of python written in javascript.  There is a project in github called filbert that does just that; interestingly enough, at this moment is also failing with the example above.

> [This brings another point which I just thought of and will file as an issue: now that the world creator can add code to be run before the user's program, the line numbers might very well be very misleading when such code is present; this will need to be investigated.]
> 
yeap.. good point.  I have not used this feature yet but I can see that it is going to need to be looked at.

**Comment by aroberge** [comment]
On Tue, May 19, 2015 at 12:37 PM, Andres Castano <notifications@github.com>
wrote:

>
> > However, since the tracebacks provided by Brython do not seem to follow
> the exact same syntax as the Python ones, I intend to use a different
> approach. First, I use the information provided by the traceback to locate
> which line is triggering the error; then, I would use the code written by
> @Goldsong <https://github.com/Goldsong> to analyze the program focusing
> around that line of code to see if more information would need to be added.
> >
> Yes.. this would work better than the stand alone code. The correct
> solutioin, which would be an interesting to work on but it is probably over
> my head, would be to use a parser of python written in javascript. There is
> a project in github called filbert that does just that; interestingly
> enough, at this moment is also failing with the example above.
>
If I go back to the original suggestion for the code analysis, it is to
guide beginners as they make some "common" mistakes.  At some point, they
will want to use Python in "real life" and have to deal with standard
tracebacks.  By catching only the "common beginner's mistakes" and add
extra information to help them understand these errors, we make the
learning curve more gentle.  There is no way (even with a complete Python
parser) that we could implement a complete set of "friendly" Python
tracebacks (i.e. covering all possible causes of errors); at some point, we
have to draw the line.   I personally find that the original suggestion by
dzo implemented by Goldsong to be pretty much all that is needed.     We
might perhaps want to catch NameError and add a suggestion about the fact
that a word has either been misspelled or that a function has not been
defined ... again, just focusing on a few errors made by beginners and
adding minimal suggestions.

More details after I've implemented the code.

**Comment by aroberge** [comment]
@dz0 , @Goldsong Check the following link:

http://reeborg.ca/world_dev.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22tokens%22%3A%22infinite%22%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%7D%5D%2C%22walls%22%3A%7B%7D%2C%22pre_code%22%3A%22print(%5C%224%20turn%20left%20follow%5C%22)%5Cnturn_left()%5Cnturn_left()%5Cnturn_left()%5Cnturn_left()%22%2C%22post_code%22%3A%22print(%5C%22goodbye%5C%22)%5Cn%20%20%20%20%5Cn%5Cn%22%7D&editor=move()%0Amove()%0Amove()%0A&library=%0Adef%20turn_right()%3A%0A%20%20%20%20repeat(turn_left%2C%203)%0A%0Adef%20turn_around()%3A%0A%20%20%20%20turn_left()%0A%20%20%20%20turn_left()%0A

It contains 5 lines of pre-code, and one error.  Whether or not the highlighting is turned off, the line number where the error occurs should be correctly identified. 

Next, I need to look at providing some additional information like this issue originally suggested (and I will need to add the translation).

**Comment by aroberge** [comment]
Simple (potential) explanation have been added for:
SyntaxError, missing semi-colon
SyntaxError, missing ( in function definition
NameError

These are ready to check before closing this issue.  (Test on http://reeborg.ca/world_def.html as usual)

**Comment by Goldsong** [comment]
My test passes

**Comment by dz0** [comment]
"[sem-colon](http://en.wikipedia.org/wiki/Semicolon)" should probably be "[colon](http://en.wikipedia.org/wiki/Colon_(punctuation))"

**Comment by dz0** [comment]
```py
move()  move()
```
says
```
Reeborg shouts: Something is wrong!

undefined

Unexpected token {```

**Comment by dz0** [comment]
missing parentheses after Reeborg command (which takes no args) seem not to be detected.. -- of course this is not Syntax, but  **Logical error** -- and that's why beginners have very little chances noticing it... 
```py
if front_is_clear:
     move()
```

I'd propose to regexp sth like this (no opening parenthesis after command):
 /\bfront_is_clear\b\s*[^(]/

for all  Reeborg commands (nontaking arguments) would probably be:
 /\b((at_goal)|(build_wall)|...|(turn_left))\b\s*[^(]/

**Comment by dz0** [comment]
1) empty lines at beginning of code  seem to be trimmed, but counted as lineno, [example](http://reeborg.ca/world_dev.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22tokens%22%3A%22infinite%22%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%7D%5D%2C%22walls%22%3A%7B%7D%7D&editor=%0A%0A%0A%0A%0A%0Amove()%0Amove()%0Amove()%0Amooov()&library=):
```py





move()
move()
move()
mooov()```

says
```
NameError

mooov

Error found at or near line **4** (should be 10)
Perhaps you misspelled a word or forgot to define a function or a variable.
```


2) And even empty lines inside program "shift"... [example2](http://reeborg.ca/world_dev.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22tokens%22%3A%22infinite%22%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%7D%5D%2C%22walls%22%3A%7B%7D%7D&editor=move()%0A%0A%0A%0A%0A%0Amove()%0Amove()%0Amove()%0Amooov()%20%20%23%20err%20line%20%2010%2C%20not%208&library=):
```py
move()





move()
move()
move()
mooov()```

says
```
NameError

mooov

Error found at or near line **8**                                         (should be 10)
Perhaps you misspelled a word or forgot to define a function or a variable.
```

**Comment by aroberge** [comment]
I have been attempting to fix the line number count; however, as I run more examples, the line reporting appears to be unreliable.  The problem I face is that I take the line reported in the traceback (by Brython) as my starting point.   Prior to execution, Brython apparently strips the empty lines at the beginning of the code; I fixed that by inserting a comment line at the beginning of the pre-code, whether or not the pre-code was present.  Furthermore, if the highlighting routine is used, it only highlights actual lines of code; so I have to count the number of "empty lines" in the code (not highlighted) and account for them.  (I probably will have to count the lines with only comments as well since they are likely skipped by the highlighting routine).

**Comment by aroberge** [comment]
See #122 for a discussion of so-called logical errors.

**Comment by aroberge** [comment]
I have used a different approach for analysing tracebacks.  Sometimes, the line number where an error occurred cannot be obtained reliably (example below); in those cases, I simply do not provide the line number information.

For example, with the highlightning turned **off**, Brython indicate that the error occurs on the first line for the program:

    move()
    
    
    for i in range(n):  # n is undefined
        move()

i.e. it gives as information the last valid line of code identified.  (with highlighting turned on, the reported line is the one providing the highlighting which I can process to extract the correct line information).

The newer version should no longer give incorrect information, even when blank lines are present.

**Comment by dz0** [comment]
if highlighting gives most of mess...
probably could rerun with highlighting turned off and get the more accurate error line number...?

**Comment by aroberge** [comment]
World_dev now uses a different Brython version; it has significantly changed the way errors are reported.  I need to almost completely rewrite the code taking care of it ...

**Comment by aroberge** [comment]
New code in place.
