### ISSUE TITLE
Dealing with Logical Errors

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#122]
From a suggestion on mentioned on #117:
---

Missing parentheses after Reeborg command (which takes no args) seem not to be detected.. -- of course this is not Syntax, but Logical error -- and that's why beginners have very little chances noticing it...

    if front_is_clear:
         move()

I'd propose to regexp sth like this (no opening parenthesis after command):
/\bfront_is_clear\b\s*[^(]/

for all Reeborg commands (nontaking arguments) would probably be: 

/\b((at_goal)|(build_wall)|...|(turn_left))\b\s*[^(]/

---
Logical Errors will not prevent program execution.  I **strongly** believe that any program that is valid Python should not be prevented from being executed, even if we could identify some "logical errors".

Perhaps we could add a "button" that could be pressed to scan for such potential logical errors as an aid for beginners - but, imo, it should be completely separate from the code execution.  Perhaps this would be like a "lint" option.

**Comment by dz0** [comment]
Yes,  warnings shouldn't prevent execusion.
Just show msg and  could highlight the suspected problem.

**Comment by aroberge** [comment]
1a) Open the additional menu.
1b) Select Javascript as the programming language
2) Write a program with some small syntax mistake (e.g. forget the parentheses, or a semi-colon)
3) Click on lint.

Would something similar for Python be appropriate?

**Comment by dz0** [comment]
Yes

But I'd like it to be activated automatically -- if Reeborg doesn't reach
goals ;)

Might be called "Hints" or "Warnings" (Lint might not mean much...)

On Wed, May 20, 2015 at 4:48 PM, André Roberge <notifications@github.com>
wrote:

> 1a) Open the additional menu.
> 1b) Select Javascript as the programming language
> 2) Write a program with some small syntax mistake (e.g. forget the
> parentheses, or a semi-colon)
> 3) Click on lint.
>
> Would something similar for Python be appropriate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aroberge/reeborg/issues/122#issuecomment-103894373>.
>



-- 
Jurgis Pralgauskis
tel: 8-616 77613;
Don't worry, be happy and make things better ;)
http://galvosukykla.lt

**Comment by aroberge** [comment]
Closing for now as it is referenced elsewhere.
