### ISSUE TITLE
Code autocomplete -- esp. for mobile devices

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#169]
After user enters 1 or 2 letters, the list of commands (or code templates like "for .. in range(..):" ) could popup. This would probably save 90% of typing time ;) 

The concept is well implemented in http://CodeCombat.com. [Code Monkey](http://playcodemonkey.com/) even has persistent buttons for command. Maybe Reeborg could  have dropdown (or slide from side) list in the editor..  This would be kind of cheatsheet.

On selecting from (autocomplete) list, command could be written with parentheses (as children tend to forget them +  on mobile devices parentheses need swiching keyboard mode, which is a bit anoying) 

ps.: During summer holidays, I'll visit some camps, where I could make crash course for children (as most have mobiles nower days).

**Comment by aroberge** [comment]
Very early on, I made a design decision to focus on laptops/desktops with decent screen size and forego any attempt to support mobile devices.

It might be possible to implement code completion using https://codemirror.net/doc/manual.html#addon_show-hint; however, I personally find that code-completion is often getting in the way.

**Comment by dz0** [comment]
I made a simple menu solution, which is handy even on nontouch devices :)
http://galvosukykla.lt/py4browser/reeborg-master/world.html see ``"Touch" komandos``

**Comment by aroberge** [comment]
Very nice solution.  I can see it as an alternative to the help ...  I may "steal" this!

**Comment by aroberge** [comment]
I implemented a first version ready for testing at http://reeborg.ca/world_dev.html  -- I will soon update http://reeborg.ca/world.html as well.   I plan to implement something that will show the language
constructs relevant based on the chosen language (Javascript or Python - I will treat Coffeescript as
equivalent to Javascript); I also intend to add more Python construct and any other commands/conditions I have missed.

Feedback welcome!

**Comment by dz0** [comment]
- ``Redo`` seems not to work (on Chrome at least)..
  - maybe also include ``for ? in ?:``
  - alongside object names, would be nice to  see their img :)

**Comment by dz0** [comment]
- ``Backspace`` would be important for touch devices (I was too lazy to implement), as Android software keyboard behaves mysteriously in CodeMirror -- ``backspace`` hides the symbols as if they are deleted, but leaves them in logical model (when you execute)

**Comment by dz0** [comment]
Maybe usability enchancement would be if commands would appear on  "hover" the category (not only when clicked)

**Comment by aroberge** [comment]
- `Backspace` on Android apparently cannot be fixed: https://github.com/codemirror/CodeMirror/issues/1196

- `redo` should work now; I had not updated the main js file after I made the change in code.

- I'm going to replace object names by images (show the text about to be inserted in the `alt` or `title` attribute); showing both names and images would take too much screen space.

- I'm planning to include other Python constructs (like a try/except clause and possibly others); perhaps I will implement `range()` as an option and only include `for ? in ?:`

**Comment by aroberge** [comment]
Images are now used instead of strings to show objects.  The name of the objects appear in the title attribute of the image and is displayed if hovering "long enough".

**Comment by aroberge** [comment]
javascript/coffeescript mode for keyboard created - not fully tested though...

**Comment by aroberge** [comment]
Closing this issue as it provides the required functionality.   I'm leaving the suggestion about showing commands when "hovering" over a category as I don't see a way to make this esthetically pleasing and useful enough to be better than simply clicking on it.
