### ISSUE TITLE
Porting old worlds to dev version (in permalinks)?

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#171]
Hi, 

if I change world.html to world_dev.html in some my permalink, the world objects are not shown... 

What would be the best way to port old worlds (with tokens/triangles/walls) to new/dev?

**Comment by aroberge** [comment]
Unfortunately, as you found out, the format is incompatible.  I could write a converter fairly easily; I will attempt to do so today.

**Comment by aroberge** [comment]
See http://reeborg.ca/conversion.html.   Note that the base url is not changed by the conversion - but, when "update" is used after copy/pasting a URL, the base url is ignored.    **Soon** the new version will be located at world.html
