### ISSUE TITLE
Conversion.js not found

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#183]
when loading http://reeborg.ca/conversion.html, I see error in console than http://reeborg.ca/src/js/utils.js is not found

and when I try to convert [old reeborg permalink](http://galvosukykla.lt/py4browser/reeborg-master/world.html?proglang=python-en&world=%7B%22tokens%22%3A%7B%223%2C1%22%3A1%7D%2C%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22tokens%22%3A0%2C%22orientation%22%3A0%2C%22prev_orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%7D%5D%2C%22goal%22%3A%7B%22tokens%22%3A%7B%226%2C1%22%3A1%7D%2C%22possible_positions%22%3A%5B%5B7%2C1%5D%5D%2C%22position%22%3A%7B%22x%22%3A7%2C%22y%22%3A1%7D%7D%7D&editor=%23%20%22grybavimo%22%20program%C4%97l%C4%97%0A%0A%23%20Pabandykite%20vykdyti%20su%20Step%20(%20%E2%96%BA%E2%96%8C)%2C%20o%20ne%20Play%20(%20%E2%96%BA)%20mytguku%0A%0Amove()%0Amove()%0Atake()%20%20%23%20paimam%20%22gryb%C4%85%22%0A%0Amove()%3B%20move()%3B%20move()%20%23%20veiksmus%20vienoj%20eilut%C4%97j%20reik%20atskirt%20kabliata%C5%A1kiais%0Aput()%20%20%20%23%20padedam%20%C4%AF%20%22krep%C5%A1%C4%AF%22%20%0A%0Amove()%20%23%20atsistojam%20fini%C5%A1e%20(meslvam%20langely)%0A&library=%23%20%27from%20my_lib%20import%20*%27%20in%20Python%20Code%20is%20required%20to%20use%0A%23%20the%20code%20in%20this%20library.%20%0A%0A), it says "Conversion.js not found"

**Comment by aroberge** [comment]
The problem should now be fixed.
