### ISSUE TITLE
Permalink Conversion with variable amount of tokens doesn't work

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#184]
Not sure if variable amount is the issue, but http://galvosukykla.lt/py4browser/reeborg-master/world.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22tokens%22%3A0%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%2C%22start_positions%22%3A%5B%5B1%2C1%5D%5D%7D%5D%2C%22walls%22%3A%7B%7D%2C%22tokens%22%3A%7B%7D%2C%22min_tokens%22%3A%7B%222%2C1%22%3A2%7D%2C%22max_tokens%22%3A%7B%222%2C1%22%3A6%7D%2C%22tokens_range%22%3A%7B%222%2C1%22%3A%222-6%22%7D%2C%22goal%22%3A%7B%22shapes%22%3A%7B%7D%7D%7D&editor=%23%20ai%C5%A1kinimuisi%20naudokite%20Step%20(%20%E2%96%BA%E2%96%8C)%20mygtuk%C4%85%0A%0A%22%22%22%20%20Komandos%20%0A%20token_here()%20--%20patikrina%2C%20ar%20esam%20ties%20%C5%BEetonu%20(gali%20j%C4%AF%20paimt)%0A%20has_token()%20--%20patikrina%2C%20ar%20turim%20%C5%BEeton%C4%85%20(galim%20j%C4%AF%20pad%C4%97t)%0A%22%22%22%0A%0A%23%20U%C5%BEduotis%3A%20%0A%23%201)%20surinkti%20kr%C5%ABvoje%20esan%C4%8Dius%20%C5%BEetonus%20(vienas%20ciklas)%0A%23%202)%20nueiti%20tiek%20%C5%BEingsni%C5%B3%2C%20kiek%20buvo%20%C5%BEeton%C5%B3%20(antras%20ciklas).%0A%23%203)%20pakilti%20%C4%AF%20vir%C5%A1%C5%B3%20tiek%2C%20kiek%20buvo%20%C5%BEeton%C5%B3%20(tre%C4%8Dias)%0A%23%20ps.%3A%20%C5%BEeton%C5%B3%20kiekis%20gali%20b%C5%ABt%20skirtingas%2C%20%0A%23%20tod%C4%97l%20pabandykite%20program%C4%85%20paleisti%20kelis%20kartus.%0A%0Athink(0)%0Amove()%0A%0An%20%3D%200%20%20%23%20%C5%BEeton%C5%B3%20skaitliukas%0A%23%20pirmas%20ciklas%0Awhile%20token_here()%3A%0A%20%20%20%20take()%0A%20%20%20%20%23....%20%20%20%23%20%C4%8Dia%20skai%C4%8Diuojam%2C%20kiek%20randam%20--%20didinam%20skaitliuk%C4%85%0A%0A%20%20%20%20%0A%23%20antras%20ciklas%3A%20i%C5%A1d%C4%97lioti%20%C5%BEetonus%20po%20vien%C4%85%20einant%20pirmyn%0A%23....%20%20%0A%20%20%20%20%23....%0A%0A%0Aturn_left()%0A%23%20tre%C4%8Dias%20ciklas%3A%20%C4%97jimas%20%C4%AF%20vir%C5%A1%C5%B3%20pagal%20skaitliuk%C4%85%0A%23....%20%20%20%20%20%20%23%20kol%20n%20daugiau%20u%C5%BE%200%20ar%20pan.%0A%20%20%20%20%23....%0A%0A%20%20%20%20%0A%23%20palikite%20%C5%A1ias%20eilutes%20pabaigoje%20%3B)%0Asay(%22Radau%20%22%2C%20n%2C%20%22%20kapeikas%22)%20%20%0Averify(%22reeborg.tokens%20%3D%3D%200%22)%0Averify(%22reeborg.x%20%3D%3D%20reeborg.y%2B1%22)%20%20%20%20%0A%0A&library= after conversion doesn't show the `2-6` token
but if I try directly the converted link (with world_old), it shows the token

**Comment by aroberge** [comment]
Bug confirmed ... I need to investigate.

**Comment by aroberge** [comment]
The problem is present in the world conversion as well (in addition to the permalink conversion).  Fixing the world conversion in src/misc/conversion.js should suffice.

**Comment by dz0** [comment]
It's a bit strange 
after conversion, in oficial site - object flashes at the beginning, but is not shown...

http://reeborg.ca/world.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%2C%22start_positions%22%3A%5B%5B1%2C1%5D%5D%2C%22objects%22%3A%7B%22token%22%3A0%7D%7D%5D%2C%22walls%22%3A%7B%7D%2C%22goal%22%3A%7B%22objects%22%3A%7B%7D%7D%2C%22objects%22%3A%7B%222%2C1%22%3A%7B%22token%22%3A%222-6%22%7D%7D%7D&editor=%23%20ai%C5%A1kinimuisi%20geriau%20naudokite%20Step%20(%20%E2%96%BA%E2%96%8C)%20mygtuk%C4%85%0A%0A%22%22%22%20%20Komandos%20%0A%20token_here()%20--%20ar%20esam%20ties%20%C5%BEetonu%20(gali%20j%C4%AF%20paimt)%0A%20has_token()%20--%20ar%20turim%20%C5%BEeton%C4%85%20(galim%20j%C4%AF%20pad%C4%97t)%0A%22%22%22%0A%0A%23%20U%C5%BEduotis%3A%20surinkti%20%C5%BEetonus%20i%C5%A1%20kr%C5%ABvos%20(vienas%20ciklas)%0A%23%20ir%20nueiti%20tiek%20%C5%BEingsni%C5%B3%2C%20kiek%20buvo%20%C5%BEeton%C5%B3%20(antras%20ciklas).%0A%23%20Kiekvienam%20%C5%BEingsny%20-%20i%C5%A1krauti%20po%20%C5%BEeton%C4%85.%0A%23%20ps.%3A%20%C5%BEeton%C5%B3%20kiekis%20gali%20b%C5%ABt%20skirtingas.%0A%0A%0Amove()%0A%0A%23%20pirmas%20ciklas%0Awhile%20token_here()%3A%0A%20%20%20%20take()%0A%0A%23%20antras%20ciklas%3A%20i%C5%A1d%C4%97lioti%20%C5%BEetonus%20po%20vien%C4%85%20einant%20pirmyn%0A%23...%20%20%20%20%23%20kol%20turim%20%C5%BEeton%C5%B3%2C%20eiti%20ir%20pad%C4%97t%0A%0Averify(%22reeborg.tokens%3D%3D0%22)%20%20%23%20palikite%20%C5%A1i%C4%85%20eilut%C4%99%20pabaigoje%20%3B)%0A%20%20%20%0A%0A&library=


**but in my earlier cloned world_dev.html version the object IS SHOWN**

http://galvosukykla.lt/py4browser/reeborg-master/world_dev.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%2C%22start_positions%22%3A%5B%5B1%2C1%5D%5D%2C%22objects%22%3A%7B%22token%22%3A0%7D%7D%5D%2C%22walls%22%3A%7B%7D%2C%22goal%22%3A%7B%22objects%22%3A%7B%7D%7D%2C%22objects%22%3A%7B%222%2C1%22%3A%7B%22token%22%3A%222-6%22%7D%7D%7D&editor=%23%20ai%C5%A1kinimuisi%20geriau%20naudokite%20Step%20(%20%E2%96%BA%E2%96%8C)%20mygtuk%C4%85%0A%0A%22%22%22%20%20Komandos%20%0A%20token_here()%20--%20ar%20esam%20ties%20%C5%BEetonu%20(gali%20j%C4%AF%20paimt)%0A%20has_token()%20--%20ar%20turim%20%C5%BEeton%C4%85%20(galim%20j%C4%AF%20pad%C4%97t)%0A%22%22%22%0A%0A%23%20U%C5%BEduotis%3A%20surinkti%20%C5%BEetonus%20i%C5%A1%20kr%C5%ABvos%20(vienas%20ciklas)%0A%23%20ir%20nueiti%20tiek%20%C5%BEingsni%C5%B3%2C%20kiek%20buvo%20%C5%BEeton%C5%B3%20(antras%20ciklas).%0A%23%20Kiekvienam%20%C5%BEingsny%20-%20i%C5%A1krauti%20po%20%C5%BEeton%C4%85.%0A%23%20ps.%3A%20%C5%BEeton%C5%B3%20kiekis%20gali%20b%C5%ABt%20skirtingas.%0A%0A%0Amove()%0A%0A%23%20pirmas%20ciklas%0Awhile%20token_here()%3A%0A%20%20%20%20take()%0A%0A%23%20antras%20ciklas%3A%20i%C5%A1d%C4%97lioti%20%C5%BEetonus%20po%20vien%C4%85%20einant%20pirmyn%0A%23...%20%20%20%20%23%20kol%20turim%20%C5%BEeton%C5%B3%2C%20eiti%20ir%20pad%C4%97t%0A%0Averify(%22reeborg.tokens%3D%3D0%22)%20%20%23%20palikite%20%C5%A1i%C4%85%20eilut%C4%99%20pabaigoje%20%3B)%0A%20%20%20%0A%0A&library=

**Comment by aroberge** [comment]
When I use one of the permalink you just posted, I get an error message in the console (URI malformed)

When I convert the first permalink you included in this bug report, and use the result, I do not get this error message.

**Comment by dz0** [comment]
Could you post your's converted version? Because mine still doesn't work (nor reeborg.ca nor mine site now) and no URL malformed  msg. in console (tried in new incognito Chrome window)

**Comment by aroberge** [comment]
http://galvosukykla.lt/py4browser/reeborg-master/world.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%2C%22start_positions%22%3A%5B%5B1%2C1%5D%5D%2C%22objects%22%3A%7B%22token%22%3A0%7D%7D%5D%2C%22walls%22%3A%7B%7D%2C%22goal%22%3A%7B%22objects%22%3A%7B%7D%7D%2C%22objects%22%3A%7B%222%2C1%22%3A%7B%22token%22%3A%222-6%22%7D%7D%7D&editor=%23%20ai%C5%A1kinimuisi%20naudokite%20Step%20(%20%E2%96%BA%E2%96%8C)%20mygtuk%C4%85%0A%0A%22%22%22%20%20Komandos%20%0A%20token_here()%20--%20patikrina%2C%20ar%20esam%20ties%20%C5%BEetonu%20(gali%20j%C4%AF%20paimt)%0A%20has_token()%20--%20patikrina%2C%20ar%20turim%20%C5%BEeton%C4%85%20(galim%20j%C4%AF%20pad%C4%97t)%0A%22%22%22%0A%0A%23%20U%C5%BEduotis%3A%20%0A%23%201)%20surinkti%20kr%C5%ABvoje%20esan%C4%8Dius%20%C5%BEetonus%20(vienas%20ciklas)%0A%23%202)%20nueiti%20tiek%20%C5%BEingsni%C5%B3%2C%20kiek%20buvo%20%C5%BEeton%C5%B3%20(antras%20ciklas).%0A%23%203)%20pakilti%20%C4%AF%20vir%C5%A1%C5%B3%20tiek%2C%20kiek%20buvo%20%C5%BEeton%C5%B3%20(tre%C4%8Dias)%0A%23%20ps.%3A%20%C5%BEeton%C5%B3%20kiekis%20gali%20b%C5%ABt%20skirtingas%2C%20%0A%23%20tod%C4%97l%20pabandykite%20program%C4%85%20paleisti%20kelis%20kartus.%0A%0Athink(0)%0Amove()%0A%0An%20%3D%200%20%20%23%20%C5%BEeton%C5%B3%20skaitliukas%0A%23%20pirmas%20ciklas%0Awhile%20token_here()%3A%0A%20%20%20%20take()%0A%20%20%20%20%23....%20%20%20%23%20%C4%8Dia%20skai%C4%8Diuojam%2C%20kiek%20randam%20--%20didinam%20skaitliuk%C4%85%0A%0A%20%20%20%20%0A%23%20antras%20ciklas%3A%20i%C5%A1d%C4%97lioti%20%C5%BEetonus%20po%20vien%C4%85%20einant%20pirmyn%0A%23....%20%20%0A%20%20%20%20%23....%0A%0A%0Aturn_left()%0A%23%20tre%C4%8Dias%20ciklas%3A%20%C4%97jimas%20%C4%AF%20vir%C5%A1%C5%B3%20pagal%20skaitliuk%C4%85%0A%23....%20%20%20%20%20%20%23%20kol%20n%20daugiau%20u%C5%BE%200%20ar%20pan.%0A%20%20%20%20%23....%0A%0A%20%20%20%20%0A%23%20palikite%20%C5%A1ias%20eilutes%20pabaigoje%20%3B)%0Asay(%22Radau%20%22%2C%20n%2C%20%22%20kapeikas%22)%20%20%0Averify(%22reeborg.tokens%20%3D%3D%200%22)%0Averify(%22reeborg.x%20%3D%3D%20reeborg.y%2B1%22)%20%20%20%20%0A%0A&library=

**Comment by aroberge** [comment]
I use the "update" button from the "permalink" option to test it.

**Comment by dz0** [comment]
Yes it works via "Permalink" paste, but not via direct URL.

**Comment by aroberge** [comment]
The problem should be fixed now.

Upon loading the site, I was loading the default world first via asynchronous ajax and then updating the world using the permalink.  However, the asynchronous call terminated after the world was loaded and replaced the world loaded via the url.
