### ISSUE TITLE
Encoding error: 'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by statkclee** [aroberge/reeborg#225]
I tried to just make html, but immediately Encoding error ... happened.

Any ideas?

-------------------------------------------------------------------------------------------

vagrant@vagrant-ubuntu-trusty-32:~/think-stat/reeborg/docs/en$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.1
WARNING: the config value 'copyright' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date

Encoding error:
'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-1ry1qP.log, if you want to report the issue to the developers.
make: *** [html] Error 1

**Comment by aroberge** [comment]
I use Python 3 and have files encoded in utf-8.  If you use Python 2, you will likely need to edit the file "conf.py" and add the prefix u in front of any string that contains non-ascii characters.

**Comment by statkclee** [comment]
I added 'u' in front of your name...copyright = u'André Roberge'

and then, it works. :-)
