### ISSUE TITLE
Test or Task ???

### ISSUE THREAD

**Issue by statkclee** [aroberge/reeborg#232]
While translating... I am confused.

Which one is correct one in the first section, Basic Tutorial? Test driven learning or Task driven learning

I think that test and task have very different implications.

Thank you

**Comment by aroberge** [comment]
What I meant was "Basic Tutorial"; when I mentioned it before, I thought it
was "done".

However, I might add an extra page or two to describe a new feature I just
added.  If you click on the editor button at the top, the editor is hidden
and what takes its place is a Python interpreter (repl) which allows to
explore things interactively.

**Comment by statkclee** [comment]
UTF-8 issue has been closed.
This is another one.

While translating... http://reeborg.ca/docs/en/ there is a sentence, "Task Driven Learning"
Meanwhile, there is another expression; "Test driven learning" in the Basic Tutorial. http://reeborg.ca/docs/en/basics/index.html

The thing is that.

**Comment by aroberge** [comment]
On Sat, Dec 5, 2015 at 11:25 AM, Kwangchun Lee <notifications@github.com>
wrote:

> UTF-8 issue has been closed.
> This is another one.
>
> While translating... http://reeborg.ca/docs/en/ there is a sentence,
> "Task Driven Learning"
> Meanwhile, there is another expression; "Test driven learning" in the
> Basic Tutorial. http://reeborg.ca/docs/en/basics/index.html
>
I wrote "test driven learning" originally (inspired by "test driven
development") but I think that "task driven learning" is a more appropriate
description, since Reeborg does not perform "tests" but rather accomplishes
"tasks".

**Comment by statkclee** [comment]
Are you going to change from "Test driven learning" to "Task driven learning" in the Basic Tutorial?

**Comment by aroberge** [comment]
On Sun, Dec 6, 2015 at 6:30 AM, Kwangchun Lee <notifications@github.com>
wrote:

> Are you going to change from "Test driven learning" to "Task driven
> learning" in the Basic Tutorial?
>
> —
>
Yes, I plan to change to Task driven learning; I will try to do this today,
soon.
