### ISSUE TITLE
Allow colors of world cells

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#258]
Collors is a nice thing, why don't have them in Reeborg? :)

Well, now once can use tiles and objects, but colors should be more easy to implement and would serve similar purpose but with more flexibility... and the worlds could be more nice - colorful..

and robot could "getcolor()" and "setcolor(...)"

**Comment by dz0** [comment]
someday you might like to use ideas from Stanford CS101 class
http://web.stanford.edu/class/cs101/image-2-exercises.html
as is demonstrated here
http://amrdraz.github.io/python-debugger/image.html

**Comment by aroberge** [comment]
`get_tile_color()` and `set_tile_color()` are definitely worthwhile additions to consider.

**Comment by aroberge** [comment]
`paint_square()` and `get_color()` or `get_colour()` are now available.
