### ISSUE TITLE
Editor enchancement: Text to blocks translation (both ways)

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#288]
There is a tool, called Droplet (https://github.com/droplet-editor/droplet), which is used by http://pencilcode.net and https://code.org/educate/applab

It implements issue request for JS and CofeeScript, and 
some explanations how to add a language (Python)
http://ideas.pencilcode.net/home/htmlcss/droplet-paper.pdf

**Comment by dz0** [comment]
oh, Droplet seems to have some of Python already :)
https://github.com/droplet-editor/droplet/blob/master/src/languages/python.coffee 

though, I havent't tried it live yet..

**Comment by MuhunKim** [comment]
@dz0 That's awesome! 
However, Reeborg language has been developed for the purpose of multi-language
(Blockly supports multiple languages)

So I think it will be not fit :(
