### ISSUE TITLE
Proposal: Timeline for stepping 

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#290]
I stumbled upon http://worrydream.com/LearnableProgramming/#flow
which has many interesting points -- but for reeborg, seems, there is all data being collected to have more advanced "replay"...
Actually Python Tutor has it, and it is convenient to "run" through instead of pressing "Next" 20 times :)

**Comment by aroberge** [comment]
What exactly would you want to see as "more advanced replay" for the robot world?  Right now, you can view a single instruction at a time (step), all of them in sequence (run), only a few at a time (insert pause statements), going back one instruction at a time (from the additional options menu).

Granted, you can only "watch" variables with a single step displayed (unlike python tutor) but the focus is on the Robot world - not on explicit values of variables ("watch") which is an additional feature.

Unless you propose to add a "slider" to select which frame is being displayed ... but I am not sure on how to integrate it in the UI in a way that would not be too overwhelming.

**Comment by dz0** [comment]
Yes, slider would be enough -- it could be underneath the world (or above
it but below navigation buttons)

On Mon, Jun 6, 2016 at 11:12 PM, André Roberge <notifications@github.com>
wrote:

> What exactly would you want to see as "more advanced replay" for the robot
> world? Right now, you can view a single instruction at a time (step), all
> of them in sequence (run), only a few at a time (insert pause statements),
> going back one instruction at a time (from the additional options menu).
>
> Granted, you can only "watch" variables with a single step displayed
> (unlike python tutor) but the focus is on the Robot world - not on explicit
> values of variables ("watch") which is an additional feature.
>
> Unless you propose to add a "slider" to select which frame is being
> displayed ... but I am not sure on how to integrate it in the UI in a way
> that would not be too overwhelming.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aroberge/reeborg/issues/290#issuecomment-224073602>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABNfM6hOosFs1PVT5zp0ysSdPMYB39wZks5qJH8RgaJpZM4IvQhk>
> .
>



-- 
Jurgis Pralgauskis
tel: 8-616 77613;
Don't worry, be happy and make things better ;)
http://galvosukykla.lt

**Comment by aroberge** [comment]
Thinking about the position ... I am thinking that it there should be some sort of way to toggle between showing the slider or showing the 4 different robot images choices.
![image](https://cloud.githubusercontent.com/assets/629698/18564948/37c09744-7b64-11e6-8ac2-c77a93279c79.png)
The choice of default image for a robot is not something that is going to be done very often in a given session; still it is something that should be fairly visible.

**Comment by aroberge** [comment]
I have created a "project" for this (new feature available on github) to keep track of its future development.  In doing so, I noticed that "projects" might not be the best use for implementing a single issue ... but it seems like something worthwhile to do at this point.

**Comment by aroberge** [comment]
Ready for testing at http://reeborg.ca/reeborg2.html
It will soon replace the default version.  (I need to implement a new way to draw the trace, so we can really step back)

Comments are most welcome.

**Comment by aroberge** [comment]
Closing this issue as this seems to be robustly implemented in the development version.
