### ISSUE TITLE
Possibility to use Skulpt instead of Brython?

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#292]
Hi, 

I guess this is brave idea, but I see skulpt is more popular in edu environments...
it has python3 flag with at least print(), division and probably input(), working.
and it has suspensions + seems to be getting [debugging](https://github.com/skulpt/skulpt/blob/master/debugger/debugger.js) functionality latelly (also some kind of debug already in [BlockPy](http://think.cs.vt.edu/blockpy/blockpy/))

So, what generally should be done to replace Brython by Skulpt for Reeborg programs?

**Comment by aroberge** [comment]
It's not going to happen.

As far as I know, there would be no way to include a user library the way I do (the second editor tab).  This is the main show stopper.

Skulpt does not support variables written using non-ascii characters; Brython does.

Brython aims to be compatible with Python 3.4 and include many modules from the standard library http://www.brython.info/static_doc/en/stdlib.html

Brython is significantly faster than skulpt https://brythonista.wordpress.com/2015/03/28/comparing-the-speed-of-cpython-brython-skulpt-and-pypy-js/

Brython's creator (Pierre Quentel) is extremely responsive when I file bugs.
