### ISSUE TITLE
Document of OOP part is contain many bug

### ISSUE THREAD

**Issue by MuhunKim** [aroberge/reeborg#294]
# Reeborg has always oil leak

# AttributeError
```console
no attribute orientation for [object Object]
```
# Solution
```python
class CompassNeedle(UsedRobot):

    def is_facing_south(self):
        # return self.body._orientation == RUR.SOUTH : AttributeError!!
        facing_south = self.body._orientation == RUR.SOUTH
        return facing_south

reeborg = CompassNeedle()
while not reeborg.is_facing_south():
    reeborg.turn_left()
```

# NameError : `inspect()`

# ReferenceError : `inspect()` is not defined

**Comment by MuhunKim** [comment]
# AttributeError : Fix
```python
class CompassNeedle(UsedRobot):

    def is_facing_south(self):
        # return self.body._orientation == RUR.SOUTH : AttributeError!!
        facing_south = self.body._orientation == RUR.SOUTH
        return facing_south

reeborg = CompassNeedle()
while not reeborg.is_facing_south():
    reeborg.turn_left()
```

**Comment by aroberge** [comment]
* the correct "fixing the leak" behaviour can be seen if the highlighting is turned off. However, it should not require this. This is a valid bug.

* `orientation` has been properly replaced by `_orientation` in the English documentation but not in the Korean documentation.  This will need to be fixed.

* `inspect` has not been defined as a synonym of `RUR.inspect()` in the newer version; this needs to be fixed.

**Comment by aroberge** [comment]
Regarding `inspect`, this was changed to `dir_js` in the code, as the output is similar to Python's `dir`. The documentation should be updated to reflect this.

**Comment by aroberge** [comment]
Documentation has been updated to use `_orientation` and `dir_js`.

Problem with leak remains.

**Comment by MuhunKim** [comment]
Thanks

**Comment by aroberge** [comment]
Problem with oil leak still remains.
