### ISSUE TITLE
Create offline version as part of build process

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#299]
A version using only local files included in the repo (instead of versions found on CDNs) should be automatically re-build (by commenting in/out some lines in reeborg.html) each time the project is built. This would allow easy working without an Internet connection.

**Comment by projetmbc** [comment]
Yes that would be great !

**Comment by aroberge** [comment]
This now works except for some missing multimedia files (images and sound) for the blockly version.

**Comment by projetmbc** [comment]
Great !

**Comment by projetmbc** [comment]
Indeed, I can't use it.

Is there something special to do either to simply open the `index.html` files ?

**Comment by aroberge** [comment]
To run either the offline or regular version locally, you do need to have a webserver running. I usually type `python -m http.server` in the directory where the html file is located and point the browser to `http://localhost:8000/reeborg_offline.html`

**Comment by projetmbc** [comment]
Ok, thats's totally logical.

You should indicate this in your Readme file.

Thanks.


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French teacher of **math** in a high school **and **amateur **Python *
*developer*

2016-09-03 22:50 GMT+02:00 André Roberge <notifications@github.com>:

**Comment by aroberge** [comment]
I had added some information ... but probably need to add more.

**Comment by projetmbc** [comment]
Great. This works well !

**Comment by aroberge** [comment]
Need to add roboto font.
