### ISSUE TITLE
More information when "A problem with your code has caused me to turn off the code highlighting"

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#305]
Hi, 
in this world, I get this situation, but don't know what to correct in the code.. The code and permalink:

```python

def turn_right():   # pseudo pasisukimas į dešinę :)
    turn_left(); 
    turn_left(); 
    turn_left();

def walk( n ):
    for i in range(n):  # n kartų paeinam
        move()          

def laiptas(  ):  # PERTVARKYTI....!!!
    # reik prametro, kurį galima būtų naudoti koamndoje walk(..) 
    turn_left()
    move()
    turn_right()
    move()
    
def iskrauk( kiek ): # PERTVARKYTI... !!!
    put()        
        
for k in range(1, 4):  # 1, 2, 3
    laiptas( )  # truputį PAKOREGUOTI
    iskrauk( k )
```

http://reeborg.ca/world.html?proglang=python-en&world=%7B%0A%20%20%22robots%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22x%22%3A%201%2C%0A%20%20%20%20%20%20%22y%22%3A%201%2C%0A%20%20%20%20%20%20%22_prev_x%22%3A%201%2C%0A%20%20%20%20%20%20%22_prev_y%22%3A%201%2C%0A%20%20%20%20%20%20%22_prev_orientation%22%3A%200%2C%0A%20%20%20%20%20%20%22objects%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22token%22%3A%2010%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22_orientation%22%3A%200%2C%0A%20%20%20%20%20%20%22start_positions%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%201%2C%0A%20%20%20%20%20%20%20%20%20%201%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%0A%20%20%5D%2C%0A%20%20%22walls%22%3A%20%7B%7D%2C%0A%20%20%22goal%22%3A%20%7B%0A%20%20%20%20%22possible_positions%22%3A%20%5B%0A%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%207%2C%0A%20%20%20%20%20%20%20%207%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%5D%2C%0A%20%20%20%20%22position%22%3A%20%7B%0A%20%20%20%20%20%20%22x%22%3A%207%2C%0A%20%20%20%20%20%20%22y%22%3A%207%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22objects%22%3A%20%7B%0A%20%20%20%20%20%20%222%2C2%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22token%22%3A%201%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%224%2C4%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22token%22%3A%202%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%227%2C7%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22token%22%3A%203%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20%22objects%22%3A%20%7B%7D%2C%0A%20%20%22small_tiles%22%3A%20false%2C%0A%20%20%22rows%22%3A%2012%2C%0A%20%20%22cols%22%3A%2014%0A%7D&editor=%23%20Veikimo%20ai%C5%A1kinimuisi%20naudokite%20Step%20(%20%E2%96%BA%E2%96%8C)%20mygtuk%C4%85%0A%22%22%22Trajektorijos%20pvz%3A%0A%20%20%20%20%20%20%20%20%20%20__%20__%20__%0A%20%20%20%20%20%20%20%20%20%7C%20%20%20%0A%20%20%20%20%20%20%20%20%20%7C%20%20%20%0A%20%20%20%20__%20__%7C%20%20%20%0A%20%20%20%7C%20%20%0A%20__%7C%20%20%0A%7C%20%0A%22%22%22%0A%0A%23%20U%C5%BEduotis.%20Pataisykite%20funkcijas%20%22laiptas%22%20ir%20%22iskrauk%22%2C%20%0A%23%20kad%20%20trajektorija%20gaut%C5%B3si%2C%20kaip%20%20did%C4%97jantys%20laiptai%0A%0Athink(0)%0Adef%20turn_right()%3A%20%20%20%23%20pseudo%20pasisukimas%20%C4%AF%20de%C5%A1in%C4%99%20%3A)%0A%20%20%20%20turn_left()%3B%20turn_left()%3B%20turn_left()%3B%0A%0Adef%20walk(%20n%20)%3A%0A%20%20%20%20for%20i%20in%20range(n)%3A%20%20%23%20n%20kart%C5%B3%20paeinam%0A%20%20%20%20%20%20%20%20move()%20%20%20%20%20%20%20%20%20%20%0A%0Adef%20laiptas(%20%20)%3A%20%20%23%20PERTVARKYTI....!!!%0A%20%20%20%20%23%20reik%20prametro%2C%20kur%C4%AF%20galima%20b%C5%ABt%C5%B3%20naudoti%20koamndoje%20walk(..)%20%0A%20%20%20%20turn_left()%0A%20%20%20%20move()%0A%20%20%20%20turn_right()%0A%20%20%20%20move()%0A%20%20%20%20%0Adef%20iskrauk(%20kiek%20)%3A%20%23%20PERTVARKYTI...%20!!!%0A%20%20%20%20put()%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%0Afor%20k%20in%20range(1%2C%204)%3A%20%20%23%201%2C%202%2C%203%0A%20%20%20%20laiptas(%20)%20%20%23%20truput%C4%AF%20PAKOREGUOTI%0A%20%20%20%20iskrauk(%20k%20)&library=%23%20%27from%20my_lib%20import%20*%27%20in%20Python%20Code%20is%20required%20to%20use%0A%23%20the%20code%20in%20this%20library.%20%0A%0A

**Comment by aroberge** [comment]
Remove the smilie ":)" on the first line of code.

**Comment by dz0** [comment]
thanks!

**Comment by aroberge** [comment]
This is now fixed.  However, unittests for this are broken since I changed the highlighting module.
