### ISSUE TITLE
Brython syntax errors are misleading quite sometimes  - ask explanation from pypyjs or other "native" python

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#355]
I guess python REPL is based on http://pypyjs.org
And it would probably give better syntax error messages.
Alternatively, some external syntax checking "service" could be used, maybe pythontutor?..

**Comment by aroberge** [comment]
The repl for Reeborg's World is something I wrote, adopted from one included with Brython. The current version is https://github.com/aroberge/reeborg/blob/master/src/python/py_repl.py

Could you give one or more examples of what you mean by the syntax error being misleading?

**Comment by aroberge** [comment]
Do you find this with the REPL only or with running the code in the editor?  I found out that the version of brython I use in the development code handles errors differently, and that some error analysis is now performed incorrectly.
