### ISSUE TITLE
Implement a nice way to increase decrease font-size in the editor.

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#387]
See https://github.com/sk-opentexts/computerscience20/issues/3

**Comment by schellenberg** [comment]
Yes, I think having zoom in/out buttons in "Additional options" would work. Perhaps overriding the behaviour of the "cmd+" and "cmd-" keyboards shortcuts would be a good idea as well...

**Comment by aroberge** [comment]
@schellenberg I would hesitate to override the behaviour of "cmd+" and "cmd-" as users might want to change the size of the entire page.

I will look at adding some additional control - perhaps a textfield to enter a value for the font size rather than having the user repeatedly press buttons until satisfied with the size.

**Comment by aroberge** [comment]
@schellenberg I have implemented a version with some buttons visible on the editors. Changing the font size in one editor changes them all. When editing a world (with 6 editors showing), the buttons are hidden as it would mess up the display with editor tabs taking two rows.

Waiting for feedback before closing this issue.

**Comment by aroberge** [comment]
Found a bug: when switching back from world-editing mode, the buttons do not reappear.

**Comment by schellenberg** [comment]
Tested this in a class environment just now. Works great!
