### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by postmodern1st** [aroberge/reeborg#458]
Good day. I'm trying to solve Hurdles tasks series and have reached the 4th one so far, but the edited code gives me an unexplained error saying "I cannot help you with this problem." Could anyone please check on my code and tell what's causing the problem?

Here's the code:
`def jump():
_while wall_on_right():
__move()

def turn_right():
_turn_left()
_turn_left()
_turn_left()
    
while not at_goal():
_while front_is_clear():
__move()
_while not front_is_clear():
__turn_left()
__jump()
__turn_right()
__move()
__turn_right()
__jump()
__if front_is_clear():
____exit()
__else:
____turn_left()

`

**Comment by aroberge** [comment]
`exit()` is a Python function that attempts to quit the entire session.  You need to use `done()`.
