### ISSUE TITLE
Tasks/Tutorial link(s) directly accessible in World.html  

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aroberge/reeborg#46]
```
Now there is proposal to open 2 windows side by side. Probably would be more 
didactic and ergonomic, if Tutorials would be integrated in main page (at least 
as link).

Now there is a list of worlds, but would be good, that when you select one, 
alongside you could see (a link to) the associated tutorial

Maybe even better would be like they have in http://learn.code.org -- the tasks 
-- and automatical checkind if you fulfill one, with following proposal to take 
the next one (you know -- gamification :) 
```

Original issue reported on code.google.com by `jurgis.pralgauskis` on 9 Jun 2014 at 2:45

**Comment by aroberge** [comment]
@dz0 Looking back at old issues which you had mentioned (like this one, and also badges), I see that I eventually got around to implement in some way most of your suggestions, even when I initially set them to "won't fix".  ;-)

See https://aroberge.github.io/reeborg-staging/?lang=en&mode=python&menu=%2Freeborg-staging%2Fworlds%2Fmenus%2Fdefault_menu_en.json&name=Other%20worlds&url=worlds%2Fmenus%2Fselect_collection_en.json for a development version (the official one is not updated quite as frequently as before).
