### ISSUE TITLE
Regarding Coffeescript

### ISSUE THREAD

**Issue by blaztoma** [aroberge/reeborg#464]
Just wanted to ask - why the Coffeescript option was removed?
Is there anything we need to know, before considering adding the support for Coffeescript?

Thanks,
Tomas

**Comment by blaztoma** [comment]
Thanks for a quick answer!
I wanted to add CoffeeScript because my kid comes from a codemonkey.com background. They have hundreds of programming tasks for kids in CoffeeScript, and it's actually good for teaching kids.
So, if there is nothing fundamentally wrong with CoffeeScript - I'll try to do it.
I also completely translated Reeborg to Lithuanian, including Lithuanian keywords, and translated Dan Schellenberg's tasks. Not sure how to contribute ATM, but I'll figure it out :) It's nice you'll retire - it is actually a fantastic project ;)

**Comment by aroberge** [comment]
You can just email me the translation files you have and I'll incorporate them.
