### ISSUE TITLE
Possible bug in wall_on_right

### ISSUE THREAD

**Issue by Sharondio** [aroberge/reeborg#479]
Working on Rain 2, and ran into this scenario:

<img width="1098" alt="Screenshot 2024-10-05 at 8 41 29 PM" src="https://github.com/user-attachments/assets/f42c6317-4c85-4195-9aab-57109b49be0a">

As you can see, the code is stepped into my check_window function. Robot does not have a wall to his right, but this function evaluated to true, and stepped into the true clause.

**Comment by aroberge** [comment]
The problem is that you did not call `wall_on_right`: you need to add parentheses to call a function.

`wall_on_right` is just the name of the function. Every function name points to an object and evaluates as `True`.

So, write `wall_on_right()` and see what happens.
