### ISSUE TITLE
Maze completes but not at xy

### ISSUE THREAD

**Issue by shockwavecs** [aroberge/reeborg#480]
Just testing a few ways to complete the maze. This code winds up saying I'm at the finish, but it's right in front of the finish line. Sometimes it completes OK, sometimes just short.

```
def turn_right():
    turn_left()
    turn_left()
    turn_left()
    
while not at_goal():
    while right_is_clear():
        turn_right()
        move()
    while wall_on_right() and not front_is_clear():
        turn_left()
    if wall_in_front():
        turn_left()
    if front_is_clear():
        move()
```

**Comment by aroberge** [comment]
Can you take a screen capture of a case where it does not complete? It should never exit the while loop until it is at the goal position.

**Comment by shockwavecs** [comment]
![Screenshot 2024-11-13 131921](https://github.com/user-attachments/assets/af5572f2-50c0-487e-8751-658050d9ea58)

**Comment by aroberge** [comment]
I don't know what's going on with your example. (Not your fault!)

I added `think(0)` as an instruction at the beginning to make it run as fast as possible. Then I just ran many simulations (probably close to 100) and it always worked (except for a case that shows a bug in your code; see below). On one of these cases, Reeborg started from the same point as in your screen capture and it did end correctly - in fewer steps that what is shown in your screen capture.
![image](https://github.com/user-attachments/assets/1c3bec09-0df5-4ef9-98eb-a31cb30df25d)

So ... I really don't understand why the code stops at the place shown in your screen capture.

BTW, here's a case that does not work with your code: it just keeps looping.

![image](https://github.com/user-attachments/assets/0cd76ffe-87b0-4267-aab5-96ba1d7b08a3)

Perhaps you can reload the page entirely and try again ...?

**Comment by shockwavecs** [comment]
That `think(0)` feature! I've been pausing and sliding along the timeline heh. 

After a force refresh of the page it seems to not do it anymore so case closed there. 
The instructor had this to solve that infinite loop. It's cool to see these and work around them. 
```
while front_is_clear():
    move()
turn_left()
```
