### ISSUE TITLE
Review javascript tutorial to reflect changes (removing strict mode, no library, etc.)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aroberge/reeborg#79]
```
Provide as complete a description of the feature request as you can,
including what pedagogical purpose it would serve (if any).  A link to a
relevant lesson might be a good addition to your description.

To be completed after issues 75-78 have been taken care of.
```

Original issue reported on code.google.com by `andre.ro...@gmail.com` on 22 Nov 2014 at 5:13

**Comment by aroberge** [comment]
I don't plan on rewriting it - not useful enough.  Instead, once the new Python one is written, I should focus on creating a good "one-pager" on transition from Python to Javascript.
