### ISSUE TITLE
"Embed as iframe" option

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#85]
It would help in courses, to have each task embeded, so children don't have to swich pages, especially if there are many tasks..  Jus hide top and bottom menus for that, and propose "embed" option in Permalink.
Trinket.io is good example https://trinket.io/embed/python/dbae6a4522

**Comment by aroberge** [comment]
I view the controls available from the menus as an essential part.  I am pretty sure that one can already use an iframe and embed Reeborg's world "as is" in a given page.

**Comment by dz0** [comment]
Students don't need World editing  (usually).

Needed windows could be preset in advance. Though help would be handy...
Maybe just leave Help button and "More menu" button (like Additional menu)..

On Mon, May 11, 2015 at 1:42 PM, André Roberge <notifications@github.com>
wrote:

> I view the controls available from the menus as an essential part. I am
> pretty sure that one can already use an iframe and embed Reeborg's world
> "as is" in a given page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aroberge/reeborg/issues/85#issuecomment-100864134>.
>



-- 
Jurgis Pralgauskis
tel: 8-616 77613;
Don't worry, be happy and make things better ;)
http://galvosukykla.lt

**Comment by aroberge** [comment]
Currently, the permalink encodes information about the world state (including user program) which is completely separate from the UI; I have changed the UI a few times in the past year, without having to worry about the permalink option.  

While the "enbed as iframe" option may appear to be desirable, it would require significant changes to the code.  Until I get a request from someone actually writing a tutorial or similar material for a course, actually embedding Reeborg's world using an iframe and wishing to selectively remove elements based on actual experience (and not as a thought experiment), I do not plan to act on this suggestion for enhancement.  This is not meant to imply that the suggestion is not an interesting one; I just want to avoid introducing unnecessary complications to the code.

**Comment by aroberge** [comment]
The permalink option now allows custom css.  Unfortunately, it does not appear to be possible to use it to change the appearance of an embedded page.

**Comment by aroberge** [comment]
Using postMessage, it is possible to modify the look of an embedded iframe.  See http://reeborg.ca/test/test_iframe.html for an example, where the "world" buttons at the bottom are hidden using css.    This should satisfy the original request.
