### ISSUE TITLE
More env. options in Permalink

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#87]
For example, I would like to get line highlighting "on" by default. 
Can I pass some option in permalink query? 

This could apply to: 
- Highligth on/off
- Diary  on/of
- Diary height 
- Editor height

**Comment by aroberge** [comment]
Currently, there are no additional options - but this seems like a potential useful enhancement.

**Comment by dz0** [comment]
As workaround there could be just option to inject JS / CSS via permalink.

Maybe with JS there is some cross site scripting vulnerability (we can ask some pro)?... but there are no personal data saved on site, so, probably no problem?

And with CSS inject'ion I could handle #85.

**Comment by aroberge** [comment]
I don't see any cross site scripting related vulnerability since, as you mentioned, there is no information saved on the site.   As I mentioned in issue #85, until a real-life use case is shown to be desirable, I do not intend to start adding options to the permalink.

Just the same, I am keeping this issue opened as an idea for enhancement.  Rather than embedding js/css code in the permalink as such, I see a possibility to define a command `change_user_interface(...)`, which could be used within a given program to do css changes.   For example, one could have something like  

    change_user_interface({'#world-edit-buttons': 'display:none', ...})

For highlighting, I could add a keyword argument to select_world to enable or disable highlighting.  Because of the simple way I implemented the highlighting feature, it breaks programs when statements span more than one line of code - I turned it off (by default) at the request of a teacher whose students were using multi-line statements to work with arrays.

Since I see a use-case for the highligthing one (from past experience), I will attempt to implement it.

**Comment by aroberge** [comment]
One important piece of information I should have provided: browsers have a maximum allowed length for URLs (and each browser has a different limit); characters beyond that limit included in a URL are just ignored.  This is why I've included an option to "update" a permalink, which bypass the browsers limitations ... but is not as user-friendly to use.

**Comment by aroberge** [comment]
I've changed the way that the highlighting is handled so that it is turned on by default.  It was turned off since it does not work (and cause runtime errors) if multiline statements are present in the program.  The new version first scan the code to see if multiline statements are present and, if that is the case, highlighting is automatically disabled with a warning to the user.

**Comment by aroberge** [comment]
See http://reeborg.ca/teaching_tricks.html#css

**Comment by dz0** [comment]
Thanks! 

ps.: "js="  might be more correct than "css=" :)

**Comment by dz0** [comment]
there is my snippet for Moodle to make live Reeborg from submited code
I give quiz with essay type questions to do the tasks and in  "manual grading" I want minimum manual work
so I put this in a HTML Block, to be able to access anytime :)

```html
<script type="text/javascript">
//<![CDATA[

function getParameterByName(url, name) {
    name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
    var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
        results = regex.exec(url);
    return results === null ? "" :  (results[1].replace(/\+/g, " "));  // decodeURIComponent
}     

function insert_answer_code_in_task_url(url, code){
    //example  some_url = "http://reeborg.ca/world.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A1%2C%22y%22%3A1%2C%22tokens%22%3A0%2C%22orientation%22%3A0%2C%22_prev_x%22%3A1%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%2C%22start_positions%22%3A%5B%5B1%2C1%5D%5D%7D%5D%2C%22walls%22%3A%7B%2211%2C1%22%3A%5B%22east%22%5D%2C%2211%2C9%22%3A%5B%22north%22%2C%22east%22%5D%2C%2210%2C9%22%3A%5B%22north%22%5D%2C%229%2C9%22%3A%5B%22north%22%5D%2C%228%2C9%22%3A%5B%22north%22%5D%2C%227%2C9%22%3A%5B%22north%22%5D%2C%226%2C9%22%3A%5B%22north%22%5D%2C%225%2C9%22%3A%5B%22north%22%5D%2C%224%2C9%22%3A%5B%22north%22%5D%2C%223%2C9%22%3A%5B%22north%22%5D%2C%222%2C9%22%3A%5B%22north%22%5D%2C%221%2C9%22%3A%5B%22north%22%5D%2C%2211%2C8%22%3A%5B%22east%22%5D%2C%2211%2C7%22%3A%5B%22east%22%5D%2C%2211%2C6%22%3A%5B%22east%22%5D%2C%2211%2C5%22%3A%5B%22east%22%5D%2C%2211%2C4%22%3A%5B%22east%22%5D%2C%2211%2C3%22%3A%5B%22east%22%5D%2C%2211%2C2%22%3A%5B%22east%22%5D%7D%2C%22goal%22%3A%7B%22tokens%22%3A%7B%226%2C5%22%3A1%7D%2C%22possible_positions%22%3A%5B%5B6%2C6%5D%5D%2C%22position%22%3A%7B%22x%22%3A6%2C%22y%22%3A6%7D%7D%2C%22tokens%22%3A%7B%226%2C1%22%3A1%7D%7D&editor=%23%20Patarimai%2C%20jei%20ka%C5%BEkur%20stringate%3A%0A%23%20%C4%AEjunkite%20veiksm%C5%B3%20pary%C5%A1kinim%C4%85%20(%22%C5%BEymeklis%22%20su%20kry%C5%BEiuku%20de%C5%A1in%C4%97j)%0A%23%20Vykdykite%20program%C4%85%20po%20%C5%BEingsn%C4%AF%20(ne%20%22Play%22%2C%20o%20%22Step%22%20mygtukas)%0A%0A%22%22%22%20Komandos%3A%0Amove()%20%20%20%20%20%20%20%20-%20%20paeina%20langel%C4%AF%20%0Aturn_left()%20%20%20-%20pasisuka%20kair%C4%97n%20(de%C5%A1in%C4%97n%20nemoka)%0Atake()%20%20%20%20%20%20%20%20-%20paima%20objekt%C4%85%20i%C5%A1%20langelio%0Aput()%20%20%20%20%20%20%20%20%20-%20padeda%20objekt%C4%85%0A%22%22%22%0A%0A%23%20A%20U%C5%BEduotis%3A%20%0A%23%20perne%C5%A1t%20%22kapeik%C4%85%22%20%C4%AF%20tu%C5%A1%C4%8Di%C4%85%20apskritim%C4%85%20%0A%23%20ir%20atsistoti%20%C4%AF%20fini%C5%A1o%20viet%C4%85%20(melsv%C4%85%20langel).%20%0A%0A%23%20pataisykite%2Fpabaikite%20program%C4%85%3A%0Amove()%0Aturn_left()%0Amove()&library=%23%20%27from%20my_lib%20import%20*%27%20in%20Python%20Code%20is%20required%20to%20use%0A%23%20the%20code%20in%20this%20library.%20%0A%0A"

    //~ url = url.replace('&editor=', '&editor=think(0)%0A')  // inject speed
    var initial_code_encoded =  getParameterByName(url, 'editor') ;
    var initial_code = decodeURIComponent(  initial_code_encoded );
    //~ alert( initial_code )
    var initial_code_commented = '#'+initial_code.replace(/\n/g, "\n# ")   // comment out old code
    
    
    var code_encoded = encodeURIComponent(initial_code_commented+"\n\n### CODE ###\nthink(0);\n\n"+code).replace(/%C2%A0/g, '')
    //~ url = url.replace('&library=', code_url_encoded+'&library=')  // just before library
    url = url.replace(initial_code_encoded, code_encoded);
    return url;
}

function code2Reeborg(){
    
    $("#q1.essay").each( function(){
        var msg = "";

        // get task url
        var task_url = ""
        var tasks = $(this).find(".formulation a[href^='http://reeborg.ca/world.html?proglang=python']").each(function(){
            
        });
        
        if (tasks.length > 1) 
            console.log( "RUR inject: "+tasks.legth+" task links found -- last taken.\n" )
        if (tasks.length == 0)             
            console.log(  "RUR inject: No task link found" )

        if (tasks.length > 0){
            task_url = tasks.last().attr('href')
        
        
            // get code
            var answer_area = $(this).find(".answer textarea").first()
            var answer_code = answer_area.text();
            
            // do inject
            var review_url = insert_answer_code_in_task_url( task_url, answer_code ); 
            // hide unneccesary and activate
            review_url += '&css='+encodeURIComponent(
                                '$("#world-edit-buttons, header").css("display", "none"); '+
                                '$(window).load( function(){  RUR.ui.run(); });'
                            )
            
            var iframe = '<iframe src="'+review_url+'"   width="100%" height="650" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>';
            //~ answer_area.text( decodeURIComponent( review_url ) ); // replace
            answer_area.replaceWith( iframe ); // replace
            
            //http://stackoverflow.com/questions/21668635/zoom-out-whole-website-using-jquery-or-css
            
        
        }

    });
    
}

//]]>
</script>


<a  onclick="code2Reeborg()" title="Robot live" style="color:grey">Transform answer boxes to live Reeborg </a>
```

**Comment by aroberge** [comment]
Good point about "js=" instead of "css="...  I will make the replacement.

As for the moodle integration ... that looks really impressive!

**Comment by aroberge** [comment]
@dz0 Would you mind contacting me by email (yours is not visible on github); I would like to find out more about your Moodle integration ... it looks like something I would possibly like to do. And, if I do so, I might be able to figure out how to make automated grading even easier. ;-)

**Comment by dz0** [comment]
this could possibly solve my  wishes for auto-tests (with varying world) #96
