### ISSUE TITLE
say()  could  take many args

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#89]
If I want to use it in "print" way, would be convenient

probably, sth like this would help
```py
def say(*args):
    output = ' '.join( [str(arg) for arg in args] )
    ...
```

**Comment by aroberge** [comment]
write() was meant to emulate print() in having multiple arguments, as in write('hello', 'world').  However, I just noticed that it doesn't, which is a bug.

**Comment by aroberge** [comment]
Bug fixed: write() can now take multiple arguments.

**Comment by dz0** [comment]
semi-topic:
but "say" is more convenient, as diary pushes my (students) editor away (down) -- they all dont line in monitor :/
I can manually change diary/editor width, but probably some css could do it ?

**Comment by aroberge** [comment]
Reopening this issue as it makes sense for `say()` to handle multiple arguments like `print()`.

**Comment by aroberge** [comment]
`say()` now handles multiple arguments.
