### ISSUE TITLE
Goal idea: Required Trail

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#91]
Tasks, that mimic turtle graphic concepts could be automatically checked by "required trail".
Like in 
http://studio.code.org/s/20-hour/stage/11/puzzle/5
or nicer http://studio.code.org/s/frozen/stage/1/puzzle/7

Now one can use walls to limit trajectory, but trail would be simpler to define. 
Could be marked as dotted/dashed line. Or as arrows if direction is important.

**Comment by aroberge** [comment]
1. While it might look nicer, what would be the pedagogical advantage of this approach compared with having a "trail of tokens" left to be picked up?    (I had thought of the idea of drawing a trail to follow before, but it would really complicate the existing code.)
2. There is already a limited capability to require the user's program to satisfy certain conditions, not easily expressible visually.  See http://reeborg.ca/teaching_tricks.html and the discussion about using "verify" - with a link to a fairly comprehensive example.
