### ISSUE TITLE
Possibility to get Blitz result

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#92]
When I am checking assignments, I would like to paste code, and see the resut at once -- without waiting for process to finish... -- maybe one more option for this?

or even better -- if page could print result in special DIV -- I could parse it automatically -- and reduce manual work (as I am going to use it in kind of MOOC) :)

**Comment by aroberge** [comment]
While not immediate, how about adding  `think(0)` as the first line of the program, and then run it?
