### ISSUE TITLE
Highlighting bug: multiline statement suspected - though there is none

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#95]
```py
# use move()
move()
move()
# :)
```
parentheses in comments seems to be suspected as multiline...

I get highlight off and msg:
"Code highlighting is only possible if no multi-line statements are present."

**Comment by aroberge** [comment]
Yes ... I have a rather primitive way of checking, simply counting the number of ( and )    as well as [ and ], and { }, and see if they match on a single line .... without taking into account that some of them could be in strings or comments...    I need to do something better.

**Comment by aroberge** [comment]
Fixed - should work if extra characters such as (){}[] are in comments or enclosed in strings: they should not be misidentified as indicating multi-line statements.
