### ISSUE TITLE
Enchancement: automatic tests by all possible start positions?

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#96]
I want  to test, that code works in all cases, without manually trying/restarting.
Could there be option "Run(Test?) all cases"? Just a loop which lists all success/failure points (grouped by case).

[Example task](http://reeborg.ca/world.html?proglang=python-en&world=%7B%22robots%22%3A%5B%7B%22x%22%3A3%2C%22y%22%3A1%2C%22tokens%22%3A0%2C%22orientation%22%3A0%2C%22_is_leaky%22%3Atrue%2C%22_prev_x%22%3A3%2C%22_prev_y%22%3A1%2C%22_prev_orientation%22%3A0%2C%22triangle%22%3A0%2C%22square%22%3A0%2C%22star%22%3A0%2C%22start_positions%22%3A%5B%5B1%2C1%5D%2C%5B3%2C1%5D%5D%7D%5D%2C%22walls%22%3A%7B%223%2C1%22%3A%5B%22east%22%5D%2C%223%2C3%22%3A%5B%22north%22%5D%2C%221%2C1%22%3A%5B%22north%22%5D%7D%2C%22goal%22%3A%7B%22possible_positions%22%3A%5B%5B5%2C2%5D%5D%2C%22position%22%3A%7B%22x%22%3A5%2C%22y%22%3A2%7D%2C%22shapes%22%3A%7B%7D%2C%22tokens%22%3A%7B%7D%7D%7D&editor=%23%20Patarimai%2C%20jei%20ka%C5%BEkas%20neveikia%3A%0A%23%20%C4%AEjunkite%20veiksm%C5%B3%20pary%C5%A1kinim%C4%85%20(%22%C5%BEymeklis%22%20su%20kry%C5%BEiuku%20de%C5%A1in%C4%97j)%0A%23%20Vykdykite%20program%C4%85%20po%20%C5%BEingsn%C4%AF%20(ne%20%22Play%22%2C%20o%20%22Step%22%20mygtukas)%0A%0A%0A%22%22%22%0ANauja%20komanda%3A%0A%0Afront_is_clear()%20--%20patikrina%2C%20ar%20galim%20eit%20pirmyn%20(n%C4%97ra%20sienos)%0A%22%22%22%0A%0A%23%20U%C5%BEduotis%3A%20nueiti%20%C4%AF%20fini%C5%A1%C4%85%2C%20nesitrankant%20%C4%AF%20sienas%0A%23%20ps.%3A%20robotas%20gali%20startuoti%20skirtingose%20vietose%0A%23%20pabandykite%20program%C4%85%20paleisti%20kelis%20kartus%0A%0A%0Awhile%20not%20at_goal()%3A%20%20%23%20kartok%2C%20kol%20nepri%C4%97jo%20fini%C5%A1o%20%0A%0A%20%20%20%20if%20front_is_clear()%3A%20%20%23%20jei%20prieky%20laisva%0A%20%20%20%20%20%20%20%20...%20%20%20%20%20%23%20%C4%AFra%C5%A1ykite%2C%20kas%20%C4%8Dia%20tikt%C5%B3%0A%20%20%20%20else%20%20%20%20%20%20%20%20%23%20pataisykite%20%C4%8Dia%20vien%C4%85%20dalyk%C4%85%0A%20%20%20%20%20%20%20%20...%20%20%20%20%20%23%20%C4%AFra%C5%A1ykite%0A&library=%23%20'from%20my_lib%20import%20*'%20in%20Python%20Code%20is%20required%20to%20use%0A%23%20the%20code%20in%20this%20library.%20%0A%0A)

**Comment by aroberge** [comment]
There is no way to do this currently ... but I can see how it would  be useful, although I am not sure how to go about and implement it given how the possible tests are set up.  One can have multiple starting positions, multiple number of tokens at a given position, etc.    Suppose one has 5 possible starting positions, with between 1 and 5 tokens located at 3 different points ... this would give us 625 possible combinations to check.

Still, usually, it probably would be much fewer ... so I will think of how it could be done.

**Comment by aroberge** [comment]
Just recording the following as an imperfect solution ....   Start by ensuring that think(0) and sound(True) are inserted at the beginning of the program.  Then, in the javascript console, run the following:

    function repeat_tests () {
        nb_tests -= 1;
        if (nb_tests < 0) return;
        RUR.ui.reload();
        RUR.ui.run();
        window.setTimeout(repeat_tests, 2000);
    }
    nb_tests = 10;
    repeat_tests();

**Comment by aroberge** [comment]
Other alternative solution:  simply create individual test worlds with specific initial conditions (which are chosen as an adequate subset of the desired one) and run the program against each of these.   Again, not ideal ....

**Comment by dz0** [comment]
maybe #107 (extra code in world) could be of use.. 

If I could inject/override logic for RUR.ui.run() a bit.;
I probably can access starting positions of robot, and loop through each to process the editor code (and then reset).
