### ISSUE TITLE
Change the code to draw generic objects.

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#98]
Related to issue #97, have a simplfied version of the code to draw objects, with the possibility of adding new ones.  For simplicity, every object should be a 40x40 pixel image with transparent background.

**Comment by Goldsong** [comment]
Will the 40x40 size be still useful if the size of the tile ends up being 48x48?

**Comment by aroberge** [comment]
I have not settled on a size yet ... when I mentioned 40x40, I was basing it on the lenth of a wall; in reality, we have a repeated pattern that is sllightly smaller.   The size matters for choosing images, but it's a minor detail when writing the code.  Let me write the code with the current size grid, add some very simple tiles and objects as test cases, and we can evaluate it at that time.

**Comment by aroberge** [comment]
Code now easily allow for generic object drawings.  If the tile size is changed, the newly written code will not have to be changed.  Closing this issue.
